### ISSUE TITLE
Zend Framework Tool Conflict

### ISSUE THREAD

**Issue by dennis-fedco** [coolcsn/CsnAuthorization#4]
I installed [Zend Framework Tool](http://framework.zend.com/manual/2.2/en/modules/zendtool.introduction.html)

When I run it, it first generates this error:

```
$ php -e vendor/zendframework/zftool/zf.php version
PHP Fatal error:  Uncaught exception 'Exception' with message 'Resource ZFTool\Controller\Info not defined' in C:\...\ZendSkeletonApplication\vendor\coolcsn\csn-authorization\src\CsnAuthorization\Module.php:56
Stack trace:
#0 [internal function]: CsnAuthorization\Module->onRoute(Object(Zend\Mvc\MvcEvent))
#1 C:\...\ZendSkeletonApplication\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#2 C:\...\ZendSkeletonApplication\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('route', Object(Zend\Mvc\MvcEvent), Object(Closure))
#3 C:\...\ZendSkeletonApplication\vendor\zendframework\zendframework\library\Zend\Mvc\Application.php(290): Zend\EventManager\EventManager->trig in C:\...\ZendSkeletonApplication\vendor\coolcsn\csn-authorization\src\CsnAuthorization\Module.php on line 56
```

It looks like there is no entry for ZFTool\Controller\Info in resource/privileges table.  But basically any access to controllers not defined in the database is barred.  And it looks like there are a few controllers that ZFTool generates that try to access things in order to list the modules.  For example, the following generates exception for a different controller:

```
php -e vendor/zendframework/zftool/zf.php list
```

It seems like ZFTool queries all controllers and the guard in CsnAuthorization, and CsnAuthorization does not allow for this to happen without first defining all ZFTool-appropriate controller and route information.  I wanted to ask about if there is a proper way of making these modules work together (and how).

**Comment by coolcsn** [comment]
Yes, we have to create role and resource for ZFTool in order to get it work. This is only a bet. I will try to do it and send you the results and observations.
